import { FilterChipSize, FilterChipType } from '../../enums';

export const filterChipVariants = [
  [
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e37',
      size: FilterChipSize.lg,
      type: FilterChipType.default,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e38',
      size: FilterChipSize.lg,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e39',
      size: FilterChipSize.lg,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e40',
      size: FilterChipSize.lg,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e47',
      size: FilterChipSize.sm,
      type: FilterChipType.default,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e48',
      size: FilterChipSize.sm,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e49',
      size: FilterChipSize.sm,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: false,
    },
    {
      id: '6cd89338-cdbc-4fd0-abab-0a3f2f800e50',
      size: FilterChipSize.sm,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: false,
    },
  ],
  [
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e37',
      size: FilterChipSize.lg,
      type: FilterChipType.default,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e38',
      size: FilterChipSize.lg,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e39',
      size: FilterChipSize.lg,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e40',
      size: FilterChipSize.lg,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e47',
      size: FilterChipSize.sm,
      type: FilterChipType.default,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e48',
      size: FilterChipSize.sm,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e49',
      size: FilterChipSize.sm,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: true,
    },
    {
      id: '7cd89338-cdbc-4fd0-abab-0a3f2f800e50',
      size: FilterChipSize.sm,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: true,
    },
  ],
  [
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e37',
      size: FilterChipSize.lg,
      type: FilterChipType.default,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e38',
      size: FilterChipSize.lg,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e39',
      size: FilterChipSize.lg,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e40',
      size: FilterChipSize.lg,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e47',
      size: FilterChipSize.sm,
      type: FilterChipType.default,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e48',
      size: FilterChipSize.sm,
      type: FilterChipType.destructive,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e49',
      size: FilterChipSize.sm,
      type: FilterChipType.outline,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
    {
      id: '6cd89338-cdbc-5fd0-abab-0a3f2f800e50',
      size: FilterChipSize.sm,
      type: FilterChipType.secondary,
      text: 'Name',
      isActive: false,
      disabled: true,
    },
  ],
];
